//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedPickup
    {
        public int Id { get; set; }
        public string DefaultRouteID { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string CustomerKey { get; set; }
        public string DriverName { get; set; }
        public string DriverMessage { get; set; }
        public string RouteName { get; set; }
        public string CustomerName { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Dispatched { get; set; }
        public Nullable<System.DateTime> DispatchTime { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Notes { get; set; }
    }
}
