//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedMessage
    {
        public int Id { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Key { get; set; }
        public Nullable<int> NumberofPendingUpdates { get; set; }
        public string Originator { get; set; }
        public string DefaultRouteId { get; set; }
        public string PreviousRouteID { get; set; }
        public bool isDragnDrop { get; set; }
    }
}
